"""Digital seed data for print quotes.

This module contains all digital pricing data extracted from the provided images.
"""

from decimal import Decimal

from quote.domain.enums import ColorMode, PrintType, Unit
from quote.repo.models import Finish, FinishPricing, Paper, PaperPricing


def create_digital_papers(db) -> dict:
    """Create papers with digital pricing for 4/4 and 4/0 color modes."""
    papers = {}

    # === COUCHE 130g BTE Y OPACO ===
    couche_130g = Paper(
        name="Couche 130g BTE y Opaco",
        weight=130,
        description="Papel couche 130g, brillo texturado y opaco",
        is_active=True,
    )
    db.add(couche_130g)
    db.flush()
    papers["couche_130g"] = couche_130g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1210.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("715.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("462.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("400.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("330.00"),
            ),
            PaperPricing(
                paper_id=couche_130g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("260.00"),
            ),
        ]
    )

    # === COUCHE 170g BTE Y OPACO ===
    couche_170g = Paper(
        name="Couche 170g BTE y Opaco",
        weight=170,
        description="Papel couche 170g, brillo texturado y opaco",
        is_active=True,
    )
    db.add(couche_170g)
    db.flush()
    papers["couche_170g"] = couche_170g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1430.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("440.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("715.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("385.00"),
            ),
            PaperPricing(
                paper_id=couche_170g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("300.00"),
            ),
        ]
    )

    # === COUCHE 200g BTE Y OPACO ===
    couche_200g = Paper(
        name="Couche 200g BTE y Opaco",
        weight=200,
        description="Papel couche 200g, brillo texturado y opaco",
        is_active=True,
    )
    db.add(couche_200g)
    db.flush()
    papers["couche_200g"] = couche_200g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1650.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1045.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("935.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("484.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("825.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("424.00"),
            ),
            PaperPricing(
                paper_id=couche_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("330.00"),
            ),
        ]
    )

    # === COUCHE 250g BTE Y OPACO ===
    couche_250g = Paper(
        name="Couche 250g BTE y Opaco",
        weight=250,
        description="Papel couche 250g, brillo texturado y opaco",
        is_active=True,
    )
    db.add(couche_250g)
    db.flush()
    papers["couche_250g"] = couche_250g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2200.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1650.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1155.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("715.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("650.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("533.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1210.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1018.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=couche_250g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("380.00"),
            ),
        ]
    )

    # === COUCHE 300g BTE Y OPACO ===
    couche_300g = Paper(
        name="Couche 300g BTE y Opaco",
        weight=300,
        description="Papel couche 300g, brillo texturado y opaco",
        is_active=True,
    )
    db.add(couche_300g)
    db.flush()
    papers["couche_300g"] = couche_300g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2530.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("2090.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1650.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("682.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("495.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1980.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1760.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1540.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("715.00"),
            ),
            PaperPricing(
                paper_id=couche_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("495.00"),
            ),
        ]
    )

    # === COUCHE 350g BTE Y OPACO ===
    couche_350g = Paper(
        name="Couche 350g BTE y Opaco",
        weight=350,
        description="Papel couche 350g, brillo texturado y opaco",
        is_active=True,
    )
    db.add(couche_350g)
    db.flush()
    papers["couche_350g"] = couche_350g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2640.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("2200.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1870.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1540.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("616.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2200.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1760.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1540.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=couche_350g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("616.00"),
            ),
        ]
    )

    # === BOND 80g ===
    bond_80g = Paper(
        name="Bond 80g",
        weight=80,
        description="Papel bond 80g para impresión digital",
        is_active=True,
    )
    db.add(bond_80g)
    db.flush()
    papers["bond_80g"] = bond_80g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("429.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("385.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("352.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("385.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("363.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("330.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("297.00"),
            ),
            PaperPricing(
                paper_id=bond_80g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("275.00"),
            ),
        ]
    )

    # === BOND 90g ===
    bond_90g = Paper(
        name="Bond 90g",
        weight=90,
        description="Papel bond 90g para impresión digital",
        is_active=True,
    )
    db.add(bond_90g)
    db.flush()
    papers["bond_90g"] = bond_90g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("363.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("385.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("385.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("363.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("330.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("297.00"),
            ),
            PaperPricing(
                paper_id=bond_90g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("275.00"),
            ),
        ]
    )

    # === BOND 104g ===
    bond_104g = Paper(
        name="Bond 104g",
        weight=104,
        description="Papel bond 104g para impresión digital",
        is_active=True,
    )
    db.add(bond_104g)
    db.flush()
    papers["bond_104g"] = bond_104g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("825.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("352.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("385.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("330.00"),
            ),
            PaperPricing(
                paper_id=bond_104g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("286.00"),
            ),
        ]
    )

    # === BOND 140g ===
    bond_140g = Paper(
        name="Bond 140g",
        weight=140,
        description="Papel bond 140g para impresión digital",
        is_active=True,
    )
    db.add(bond_140g)
    db.flush()
    papers["bond_140g"] = bond_140g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1210.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("715.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("500.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("429.00"),
            ),
            PaperPricing(
                paper_id=bond_140g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("385.00"),
            ),
        ]
    )

    # === KRAFT 200g ===
    kraft_200g = Paper(
        name="Kraft 200g",
        weight=200,
        description="Papel kraft 200g para impresión digital",
        is_active=True,
    )
    db.add(kraft_200g)
    db.flush()
    papers["kraft_200g"] = kraft_200g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("429.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("385.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("715.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("495.00"),
            ),
            PaperPricing(
                paper_id=kraft_200g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("330.00"),
            ),
        ]
    )

    # === KRAFT 300g ===
    kraft_300g = Paper(
        name="Kraft 300g",
        weight=300,
        description="Papel kraft 300g para impresión digital",
        is_active=True,
    )
    db.add(kraft_300g)
    db.flush()
    papers["kraft_300g"] = kraft_300g

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1430.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("440.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1045.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=kraft_300g.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("385.00"),
            ),
        ]
    )

    # === CARTULINA DUPLEX ===
    cartulina_duplex = Paper(
        name="Cartulina Duplex",
        weight=270,
        description="Cartulina duplex 270g rev. blanco",
        is_active=True,
    )
    db.add(cartulina_duplex)
    db.flush()
    papers["cartulina_duplex"] = cartulina_duplex

    # Digital pricing 4/4 - Nota: sin precio en rango 1-5 según imagen
    db.add_all(
        [
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1650.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1155.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("715.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("528.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1210.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1100.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1045.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("605.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=cartulina_duplex.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("385.00"),
            ),
        ]
    )

    # === OPALINA LISA 246g ===
    opalina_lisa = Paper(
        name="Opalina Lisa 246g",
        weight=246,
        description="Opalina lisa 246g para impresión digital",
        is_active=True,
    )
    db.add(opalina_lisa)
    db.flush()
    papers["opalina_lisa"] = opalina_lisa

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2640.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("2200.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1870.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1540.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("616.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2200.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1760.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1540.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1430.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1210.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=opalina_lisa.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("715.00"),
            ),
        ]
    )

    # === OPALINA TEXTURADA 246g ===
    opalina_texturada = Paper(
        name="Opalina Texturada 246g",
        weight=246,
        description="Opalina texturada 246g para impresión digital",
        is_active=True,
    )
    db.add(opalina_texturada)
    db.flush()
    papers["opalina_texturada"] = opalina_texturada

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2640.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("2200.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1870.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1540.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("616.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2200.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1980.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1650.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1430.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("1210.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("825.00"),
            ),
            PaperPricing(
                paper_id=opalina_texturada.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("605.00"),
            ),
        ]
    )

    # === CARTULINA SOLIDA 240g ===
    cartulina_solida = Paper(
        name="Cartulina Solida 240g",
        weight=240,
        description="Cartulina solida 240g para impresión digital",
        is_active=True,
    )
    db.add(cartulina_solida)
    db.flush()
    papers["cartulina_solida"] = cartulina_solida

    # Digital pricing 4/4
    db.add_all(
        [
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1650.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1320.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1045.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("935.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("418.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("990.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("880.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("825.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=201,
                max_quantity=300,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=301,
                max_quantity=500,
                unit_price=Decimal("418.00"),
            ),
            PaperPricing(
                paper_id=cartulina_solida.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("352.00"),
            ),
        ]
    )

    # === POLIMATE ===
    polimate = Paper(
        name="Polimate",
        weight=150,
        description="Polimate para impresión digital",
        is_active=True,
    )
    db.add(polimate)
    db.flush()
    papers["polimate"] = polimate

    # Digital pricing 4/4 - Solo 5 rangos según imagen
    db.add_all(
        [
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_4,
                min_quantity=101,
                max_quantity=None,
                unit_price=Decimal("330.00"),
            ),
        ]
    )

    # Digital pricing 4/0
    db.add_all(
        [
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("770.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("660.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("550.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("440.00"),
            ),
            PaperPricing(
                paper_id=polimate.id,
                print_type=PrintType.DIGITAL,
                color_mode=ColorMode.C4_0,
                min_quantity=101,
                max_quantity=None,
                unit_price=Decimal("330.00"),
            ),
        ]
    )

    return papers


def create_digital_finishes(db) -> dict:
    """Create finishes with digital pricing only."""
    finishes = {}

    # === CORTE GUILLOTINA ===
    corte_guillotina = Finish(
        name="Corte Guillotina",
        description="Corte con guillotina (total)",
        is_active=True,
    )
    db.add(corte_guillotina)
    db.flush()
    finishes["corte_guillotina"] = corte_guillotina

    # Digital pricing
    db.add_all(
        [
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("3000.00"),
            ),
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("3000.00"),
            ),
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("3000.00"),
            ),
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("4000.00"),
            ),
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("5000.00"),
            ),
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=201,
                max_quantity=500,
                unit_price=Decimal("7000.00"),
            ),
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=501,
                max_quantity=1000,
                unit_price=Decimal("8500.00"),
            ),
            FinishPricing(
                finish_id=corte_guillotina.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=1001,
                max_quantity=None,
                unit_price=Decimal("10000.00"),
            ),
        ]
    )

    # === PLISADO/PREPICADO ===
    plisado = Finish(
        name="Plisado/Prepicado",
        description="Plisado o prepicado por pliegue",
        is_active=True,
    )
    db.add(plisado)
    db.flush()
    finishes["plisado"] = plisado

    # Digital pricing
    db.add_all(
        [
            FinishPricing(
                finish_id=plisado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("20.00"),
            ),
            FinishPricing(
                finish_id=plisado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("20.00"),
            ),
            FinishPricing(
                finish_id=plisado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("20.00"),
            ),
            FinishPricing(
                finish_id=plisado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("20.00"),
            ),
            FinishPricing(
                finish_id=plisado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("20.00"),
            ),
            FinishPricing(
                finish_id=plisado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=201,
                max_quantity=500,
                unit_price=Decimal("12.00"),
            ),
            FinishPricing(
                finish_id=plisado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("10.00"),
            ),
        ]
    )

    # === ANILLADO ===
    anillado = Finish(
        name="Anillado",
        description="Anillado por libro",
        is_active=True,
    )
    db.add(anillado)
    db.flush()
    finishes["anillado"] = anillado

    # Digital pricing
    db.add_all(
        [
            FinishPricing(
                finish_id=anillado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1500.00"),
            ),
            FinishPricing(
                finish_id=anillado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1200.00"),
            ),
            FinishPricing(
                finish_id=anillado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("1200.00"),
            ),
            FinishPricing(
                finish_id=anillado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("1000.00"),
            ),
            FinishPricing(
                finish_id=anillado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("800.00"),
            ),
            FinishPricing(
                finish_id=anillado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=201,
                max_quantity=500,
                unit_price=Decimal("700.00"),
            ),
            FinishPricing(
                finish_id=anillado.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("500.00"),
            ),
        ]
    )

    # === PLOTTER CORTE ===
    plotter_corte = Finish(
        name="Plotter Corte",
        description="Corte con plotter por pliego",
        is_active=True,
    )
    db.add(plotter_corte)
    db.flush()
    finishes["plotter_corte"] = plotter_corte

    # Digital pricing - Nota: en imagen 4/4 no hay valores, pero en 4/0 sí
    db.add_all(
        [
            FinishPricing(
                finish_id=plotter_corte.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("800.00"),
            ),
            FinishPricing(
                finish_id=plotter_corte.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("500.00"),
            ),
            FinishPricing(
                finish_id=plotter_corte.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("500.00"),
            ),
            FinishPricing(
                finish_id=plotter_corte.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("400.00"),
            ),
            FinishPricing(
                finish_id=plotter_corte.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=101,
                max_quantity=None,
                unit_price=Decimal("200.00"),
            ),
        ]
    )

    # === OJETILLOS ===
    ojetillos = Finish(
        name="Ojetillos",
        description="Colocación de ojetillos",
        is_active=True,
    )
    db.add(ojetillos)
    db.flush()
    finishes["ojetillos"] = ojetillos

    # Digital pricing
    db.add_all(
        [
            FinishPricing(
                finish_id=ojetillos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("800.00"),
            ),
            FinishPricing(
                finish_id=ojetillos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("500.00"),
            ),
            FinishPricing(
                finish_id=ojetillos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=21,
                max_quantity=100,
                unit_price=Decimal("500.00"),
            ),
            FinishPricing(
                finish_id=ojetillos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.PER_ITEM,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("400.00"),
            ),
        ]
    )

    # === TROQUELADO POCOS PRODUCTOS ===
    troquel_pocos = Finish(
        name="Troquelado Pocos Productos",
        description="Troquelado o medio corte - pocos productos en pliego",
        is_active=True,
    )
    db.add(troquel_pocos)
    db.flush()
    finishes["troquel_pocos"] = troquel_pocos

    # Digital pricing
    db.add_all(
        [
            FinishPricing(
                finish_id=troquel_pocos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("1000.00"),
            ),
            FinishPricing(
                finish_id=troquel_pocos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("700.00"),
            ),
            FinishPricing(
                finish_id=troquel_pocos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("450.00"),
            ),
            FinishPricing(
                finish_id=troquel_pocos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("400.00"),
            ),
            FinishPricing(
                finish_id=troquel_pocos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("300.00"),
            ),
            FinishPricing(
                finish_id=troquel_pocos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=201,
                max_quantity=500,
                unit_price=Decimal("280.00"),
            ),
            FinishPricing(
                finish_id=troquel_pocos.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("80000.00"),
            ),
        ]
    )

    # === TROQUELADO VARIOS PRODUCTOS ===
    troquel_varios = Finish(
        name="Troquelado Varios Productos",
        description="Troquelado o medio corte - varios productos en pliego",
        is_active=True,
    )
    db.add(troquel_varios)
    db.flush()
    finishes["troquel_varios"] = troquel_varios

    # Digital pricing
    db.add_all(
        [
            FinishPricing(
                finish_id=troquel_varios.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=1,
                max_quantity=5,
                unit_price=Decimal("2000.00"),
            ),
            FinishPricing(
                finish_id=troquel_varios.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=6,
                max_quantity=20,
                unit_price=Decimal("1200.00"),
            ),
            FinishPricing(
                finish_id=troquel_varios.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=21,
                max_quantity=50,
                unit_price=Decimal("800.00"),
            ),
            FinishPricing(
                finish_id=troquel_varios.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=51,
                max_quantity=100,
                unit_price=Decimal("750.00"),
            ),
            FinishPricing(
                finish_id=troquel_varios.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=101,
                max_quantity=200,
                unit_price=Decimal("100000.00"),
            ),
            FinishPricing(
                finish_id=troquel_varios.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=201,
                max_quantity=500,
                unit_price=Decimal("100000.00"),
            ),
            FinishPricing(
                finish_id=troquel_varios.id,
                print_type=PrintType.DIGITAL,
                unit=Unit.JOB,
                min_quantity=501,
                max_quantity=None,
                unit_price=Decimal("100000.00"),
            ),
        ]
    )

    return finishes
