create type public.plotterbillingmetric as enum ('SQM', 'JOB_QUANTITY');

create table public.plotter_pricing (
  id bigint generated by default as identity primary key,
  paper_id bigint references public.papers(id),
  finish_id bigint references public.finishes(id),
  billing_metric public.plotterbillingmetric not null,
  minimum numeric(10, 2) not null,
  maximum numeric(10, 2) not null,
  unit_price numeric(12, 2) not null,
  currency varchar(3) not null default 'CLP' check (currency = 'CLP'),
  check ((paper_id is null) <> (finish_id is null)),
  check (minimum >= 0),
  check (maximum >= minimum),
  check (unit_price > 0)
);

create unique index plotter_pricing_paper_rate_idx
  on public.plotter_pricing (paper_id, billing_metric, minimum, maximum)
  where paper_id is not null;
create unique index plotter_pricing_finish_rate_idx
  on public.plotter_pricing (finish_id, billing_metric, minimum, maximum)
  where finish_id is not null;

alter table public.plotter_pricing enable row level security;
