-- Internal production costs are a separate catalog and never replace selling prices.
create table public.paper_internal_costs (
  id bigint generated by default as identity primary key,
  paper_id bigint not null references public.papers(id) on delete cascade,
  print_type public.printtype not null,
  unit public.unit not null,
  paper_cost numeric(12, 2) check (paper_cost >= 0),
  printing_cost numeric(12, 2) check (printing_cost >= 0),
  check (paper_cost is not null or printing_cost is not null),
  check ((print_type in ('DIGITAL', 'OFFSET') and unit = 'SHEET')
      or (print_type = 'PLOTTER' and unit = 'SQM')),
  unique (paper_id, print_type)
);

create table public.finish_internal_costs (
  id bigint generated by default as identity primary key,
  finish_id bigint not null references public.finishes(id) on delete cascade,
  print_type public.printtype not null,
  unit public.unit not null,
  unit_cost numeric(12, 2) not null check (unit_cost >= 0),
  check (unit = 'SHEET'),
  unique (finish_id, print_type)
);

alter table public.quote_items
  add column internal_paper_cost numeric(12, 2),
  add column internal_printing_cost numeric(12, 2),
  add column internal_finishing_cost numeric(12, 2),
  add column internal_cost_total numeric(12, 2),
  add column internal_cost_snapshot jsonb;

alter table public.paper_internal_costs enable row level security;
alter table public.finish_internal_costs enable row level security;
