-- Supabase is the schema authority. Browser roles receive no public-table policies;
-- FastAPI connects with its backend database credential and performs authorization itself.

create type public.userrole as enum ('SUPER_ADMIN', 'ADMIN', 'VENDEDOR');
create type public.clienttype as enum ('INDIVIDUAL', 'COMPANY');
create type public.quotestatus as enum ('DRAFT', 'SENT', 'APPROVED', 'REJECTED');
create type public.printtype as enum ('DIGITAL', 'OFFSET', 'PLOTTER');
create type public.colormode as enum ('C4_0', 'C4_4');
create type public.unit as enum ('SHEET', 'SQM', 'PER_1000', 'JOB', 'PER_ITEM');

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role public.userrole not null default 'VENDEDOR',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz,
  deleted_at timestamptz
);

create table public.legacy_user_migrations (
  legacy_user_id bigint primary key,
  user_id uuid not null unique references public.users(id) on delete cascade,
  migrated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.create_auth_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, name, email)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', new.email), new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger auth_user_profile
after insert on auth.users
for each row execute procedure public.create_auth_profile();

create table public.clients (
  id bigint generated by default as identity primary key,
  client_type public.clienttype not null,
  email text,
  phone text,
  address text,
  tax_id text not null,
  first_name text,
  last_name text,
  company_name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz,
  deleted_at timestamptz,
  created_by_id uuid references public.users(id)
);
create index clients_tax_id_idx on public.clients(tax_id);

create table public.papers (
  id bigint generated by default as identity primary key,
  name text not null,
  weight integer not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz,
  deleted_at timestamptz
);

create table public.finishes (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz,
  deleted_at timestamptz
);

create table public.base_measurements (
  id bigint generated by default as identity primary key,
  name text not null,
  width numeric(8, 2) not null,
  height numeric(8, 2) not null,
  description text,
  is_active boolean not null default true
);

create table public.paper_pricing (
  id bigint generated by default as identity primary key,
  paper_id bigint not null references public.papers(id),
  print_type public.printtype not null,
  color_mode public.colormode,
  min_quantity integer not null check (min_quantity >= 1),
  max_quantity integer check (max_quantity >= min_quantity),
  unit_price numeric(10, 2) not null
);

create table public.finish_pricing (
  id bigint generated by default as identity primary key,
  finish_id bigint not null references public.finishes(id),
  print_type public.printtype not null,
  unit public.unit not null,
  min_quantity integer not null check (min_quantity >= 1),
  max_quantity integer check (max_quantity >= min_quantity),
  unit_price numeric(10, 2) not null
);

create table public.quotes (
  id bigint generated by default as identity primary key,
  quote_number text not null unique,
  status public.quotestatus not null default 'DRAFT',
  seller_id uuid not null references public.users(id),
  client_id bigint not null references public.clients(id),
  subtotal numeric(12, 2) not null default 0,
  tax numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz,
  sent_at timestamptz
);

create table public.quote_items (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.quotes(id) on delete cascade,
  paper_id bigint references public.papers(id),
  name text not null,
  description text,
  print_type public.printtype not null,
  color_mode public.colormode not null,
  width numeric(8, 2) not null,
  height numeric(8, 2) not null,
  quantity integer not null check (quantity >= 1),
  paper_unit_price numeric(10, 2) not null,
  pieces_per_sheet integer,
  sheets_needed integer,
  total_sheets_with_merma integer,
  square_meters numeric(8, 2),
  material_cost numeric(12, 2) not null default 0,
  finishing_cost numeric(12, 2) not null default 0,
  plates_cost numeric(12, 2) not null default 0,
  run_cost numeric(12, 2) not null default 0,
  fixed_costs numeric(12, 2) not null default 0,
  paper_cost numeric(12, 2) not null default 0,
  loss_percentage double precision not null default 0,
  subtotal_before_losses numeric(12, 2) not null default 0,
  subtotal_with_losses numeric(12, 2) not null default 0,
  iva_amount numeric(12, 2) not null default 0,
  total_final numeric(12, 2) not null default 0,
  details_json jsonb
);

create table public.quote_item_finishes (
  id bigint generated by default as identity primary key,
  quote_item_id bigint not null references public.quote_items(id) on delete cascade,
  finish_id bigint not null references public.finishes(id),
  unit_price numeric(10, 2) not null
);

create table public.fixed_products (
  id uuid primary key,
  product_id text not null unique,
  name text not null,
  print_type text not null,
  client_id bigint references public.clients(id),
  base_quote_snapshot jsonb not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz
);

create table public.fixed_product_quantity_ranges (
  id uuid primary key,
  fixed_product_id uuid not null references public.fixed_products(id) on delete cascade,
  min_quantity integer not null check (min_quantity >= 1),
  max_quantity integer not null check (max_quantity >= min_quantity),
  unit_price numeric(12, 2) not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (fixed_product_id, min_quantity, max_quantity)
);

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'users', 'legacy_user_migrations', 'clients', 'papers', 'finishes', 'base_measurements', 'paper_pricing',
    'finish_pricing', 'quotes', 'quote_items', 'quote_item_finishes', 'fixed_products',
    'fixed_product_quantity_ranges'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;
